-- Merge manually-typed games into the BoardGameGeek-linked entry with the same
-- title (e.g. a hand-added "7 Wonders" alongside the real one). The BGG row is
-- richer, so it wins; references are repointed and colliding rows dropped.
UPDATE OR IGNORE `nominations` SET `game_id` = (SELECT MIN(g2.id) FROM `games` g2 WHERE g2.bgg_id IS NOT NULL AND LOWER(g2.title) = (SELECT LOWER(g1.title) FROM `games` g1 WHERE g1.id = `nominations`.`game_id`)) WHERE `game_id` IN (SELECT g.id FROM `games` g WHERE g.bgg_id IS NULL AND EXISTS (SELECT 1 FROM `games` g3 WHERE g3.bgg_id IS NOT NULL AND LOWER(g3.title) = LOWER(g.title)));--> statement-breakpoint
UPDATE OR IGNORE `approvals` SET `game_id` = (SELECT MIN(g2.id) FROM `games` g2 WHERE g2.bgg_id IS NOT NULL AND LOWER(g2.title) = (SELECT LOWER(g1.title) FROM `games` g1 WHERE g1.id = `approvals`.`game_id`)) WHERE `game_id` IN (SELECT g.id FROM `games` g WHERE g.bgg_id IS NULL AND EXISTS (SELECT 1 FROM `games` g3 WHERE g3.bgg_id IS NOT NULL AND LOWER(g3.title) = LOWER(g.title)));--> statement-breakpoint
UPDATE OR IGNORE `plays` SET `game_id` = (SELECT MIN(g2.id) FROM `games` g2 WHERE g2.bgg_id IS NOT NULL AND LOWER(g2.title) = (SELECT LOWER(g1.title) FROM `games` g1 WHERE g1.id = `plays`.`game_id`)) WHERE `game_id` IN (SELECT g.id FROM `games` g WHERE g.bgg_id IS NULL AND EXISTS (SELECT 1 FROM `games` g3 WHERE g3.bgg_id IS NOT NULL AND LOWER(g3.title) = LOWER(g.title)));--> statement-breakpoint
DELETE FROM `nominations` WHERE `game_id` IN (SELECT g.id FROM `games` g WHERE g.bgg_id IS NULL AND EXISTS (SELECT 1 FROM `games` g3 WHERE g3.bgg_id IS NOT NULL AND LOWER(g3.title) = LOWER(g.title)));--> statement-breakpoint
DELETE FROM `approvals` WHERE `game_id` IN (SELECT g.id FROM `games` g WHERE g.bgg_id IS NULL AND EXISTS (SELECT 1 FROM `games` g3 WHERE g3.bgg_id IS NOT NULL AND LOWER(g3.title) = LOWER(g.title)));--> statement-breakpoint
DELETE FROM `plays` WHERE `game_id` IN (SELECT g.id FROM `games` g WHERE g.bgg_id IS NULL AND EXISTS (SELECT 1 FROM `games` g3 WHERE g3.bgg_id IS NOT NULL AND LOWER(g3.title) = LOWER(g.title)));--> statement-breakpoint
DELETE FROM `games` WHERE `bgg_id` IS NULL AND EXISTS (SELECT 1 FROM `games` g3 WHERE g3.bgg_id IS NOT NULL AND LOWER(g3.title) = LOWER(`games`.`title`));
